---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-rcs-rcs-dana-io-v1alpha1-cappconfig
  failurePolicy: Fail
  name: mcappconfig-v1alpha1.kb.io
  rules:
  - apiGroups:
    - rcs.rcs.dana.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cappconfigs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-rcs-rcs-dana-io-v1alpha1-cappconfig
  failurePolicy: Fail
  name: vcappconfig-v1alpha1.kb.io
  rules:
  - apiGroups:
    - rcs.rcs.dana.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cappconfigs
  sideEffects: None
