---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cappconfigs.rcs.dana.io
spec:
  group: rcs.dana.io
  names:
    kind: CappConfig
    plural: cappconfigs
    singular: cappconfig
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                dnsConfig:
                  type: object
                  properties:
                    zone:
                      type: string
                    cname:
                      type: string
                    provider:
                      type: string
                    issuer:
                      type: string
                autoscaleConfig:
                  type: object
                  properties:
                    rps:
                      type: string
                    cpu:
                      type: string
                    memory:
                      type: string
                    concurrency:
                      type: string
                    activationScale:
                      type: string