apiVersion: rcs.dana.io/v1alpha1
kind: Capp
metadata:
  name: koki
  "annotations": {
  }
spec:
  configurationSpec:
    template:
      metadata:
        creationTimestamp: null
      spec:
        containers:
          - env:
              - name: APP_NAME
                value: capp-with-cluster
            image: ghcr.io/knative/autoscale-go:latest
            name: capp-with-cluster
            resources: { }
  routeSpec:
    hostname: rbacqwegen.dev
  scaleMetric: cpu
