//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationLinks) DeepCopyInto(out *ApplicationLinks) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationLinks.
func (in *ApplicationLinks) DeepCopy() *ApplicationLinks {
	if in == nil {
		return nil
	}
	out := new(ApplicationLinks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthEnvTarget) DeepCopyInto(out *AuthEnvTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthEnvTarget.
func (in *AuthEnvTarget) DeepCopy() *AuthEnvTarget {
	if in == nil {
		return nil
	}
	out := new(AuthEnvTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthSecretTarget) DeepCopyInto(out *AuthSecretTarget) {
	*out = *in
	in.SecretRef.DeepCopyInto(&out.SecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthSecretTarget.
func (in *AuthSecretTarget) DeepCopy() *AuthSecretTarget {
	if in == nil {
		return nil
	}
	out := new(AuthSecretTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscaleConfig) DeepCopyInto(out *AutoscaleConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscaleConfig.
func (in *AutoscaleConfig) DeepCopy() *AutoscaleConfig {
	if in == nil {
		return nil
	}
	out := new(AutoscaleConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Capp) DeepCopyInto(out *Capp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Capp.
func (in *Capp) DeepCopy() *Capp {
	if in == nil {
		return nil
	}
	out := new(Capp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Capp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappBuild) DeepCopyInto(out *CappBuild) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappBuild.
func (in *CappBuild) DeepCopy() *CappBuild {
	if in == nil {
		return nil
	}
	out := new(CappBuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CappBuild) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappBuildClusterStrategyConfig) DeepCopyInto(out *CappBuildClusterStrategyConfig) {
	*out = *in
	out.BuildFile = in.BuildFile
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappBuildClusterStrategyConfig.
func (in *CappBuildClusterStrategyConfig) DeepCopy() *CappBuildClusterStrategyConfig {
	if in == nil {
		return nil
	}
	out := new(CappBuildClusterStrategyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappBuildConfig) DeepCopyInto(out *CappBuildConfig) {
	*out = *in
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(CappBuildOutputConfig)
		**out = **in
	}
	out.ClusterBuildStrategy = in.ClusterBuildStrategy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappBuildConfig.
func (in *CappBuildConfig) DeepCopy() *CappBuildConfig {
	if in == nil {
		return nil
	}
	out := new(CappBuildConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappBuildFile) DeepCopyInto(out *CappBuildFile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappBuildFile.
func (in *CappBuildFile) DeepCopy() *CappBuildFile {
	if in == nil {
		return nil
	}
	out := new(CappBuildFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappBuildFileStrategyConfig) DeepCopyInto(out *CappBuildFileStrategyConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappBuildFileStrategyConfig.
func (in *CappBuildFileStrategyConfig) DeepCopy() *CappBuildFileStrategyConfig {
	if in == nil {
		return nil
	}
	out := new(CappBuildFileStrategyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappBuildGitSource) DeepCopyInto(out *CappBuildGitSource) {
	*out = *in
	if in.CloneSecret != nil {
		in, out := &in.CloneSecret, &out.CloneSecret
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappBuildGitSource.
func (in *CappBuildGitSource) DeepCopy() *CappBuildGitSource {
	if in == nil {
		return nil
	}
	out := new(CappBuildGitSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappBuildList) DeepCopyInto(out *CappBuildList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CappBuild, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappBuildList.
func (in *CappBuildList) DeepCopy() *CappBuildList {
	if in == nil {
		return nil
	}
	out := new(CappBuildList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CappBuildList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappBuildOutput) DeepCopyInto(out *CappBuildOutput) {
	*out = *in
	if in.PushSecret != nil {
		in, out := &in.PushSecret, &out.PushSecret
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappBuildOutput.
func (in *CappBuildOutput) DeepCopy() *CappBuildOutput {
	if in == nil {
		return nil
	}
	out := new(CappBuildOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappBuildOutputConfig) DeepCopyInto(out *CappBuildOutputConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappBuildOutputConfig.
func (in *CappBuildOutputConfig) DeepCopy() *CappBuildOutputConfig {
	if in == nil {
		return nil
	}
	out := new(CappBuildOutputConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappBuildRebuild) DeepCopyInto(out *CappBuildRebuild) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappBuildRebuild.
func (in *CappBuildRebuild) DeepCopy() *CappBuildRebuild {
	if in == nil {
		return nil
	}
	out := new(CappBuildRebuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappBuildSource) DeepCopyInto(out *CappBuildSource) {
	*out = *in
	in.Git.DeepCopyInto(&out.Git)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappBuildSource.
func (in *CappBuildSource) DeepCopy() *CappBuildSource {
	if in == nil {
		return nil
	}
	out := new(CappBuildSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappBuildSpec) DeepCopyInto(out *CappBuildSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	out.BuildFile = in.BuildFile
	if in.Rebuild != nil {
		in, out := &in.Rebuild, &out.Rebuild
		*out = new(CappBuildRebuild)
		**out = **in
	}
	in.Output.DeepCopyInto(&out.Output)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappBuildSpec.
func (in *CappBuildSpec) DeepCopy() *CappBuildSpec {
	if in == nil {
		return nil
	}
	out := new(CappBuildSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappBuildStatus) DeepCopyInto(out *CappBuildStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappBuildStatus.
func (in *CappBuildStatus) DeepCopy() *CappBuildStatus {
	if in == nil {
		return nil
	}
	out := new(CappBuildStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappConfig) DeepCopyInto(out *CappConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappConfig.
func (in *CappConfig) DeepCopy() *CappConfig {
	if in == nil {
		return nil
	}
	out := new(CappConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CappConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappConfigList) DeepCopyInto(out *CappConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CappConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappConfigList.
func (in *CappConfigList) DeepCopy() *CappConfigList {
	if in == nil {
		return nil
	}
	out := new(CappConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CappConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappConfigSpec) DeepCopyInto(out *CappConfigSpec) {
	*out = *in
	out.DNSConfig = in.DNSConfig
	out.AutoscaleConfig = in.AutoscaleConfig
	in.DefaultResources.DeepCopyInto(&out.DefaultResources)
	if in.AllowedHostnamePatterns != nil {
		in, out := &in.AllowedHostnamePatterns, &out.AllowedHostnamePatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CappBuild != nil {
		in, out := &in.CappBuild, &out.CappBuild
		*out = new(CappBuildConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappConfigSpec.
func (in *CappConfigSpec) DeepCopy() *CappConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CappConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappConfigStatus) DeepCopyInto(out *CappConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappConfigStatus.
func (in *CappConfigStatus) DeepCopy() *CappConfigStatus {
	if in == nil {
		return nil
	}
	out := new(CappConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappList) DeepCopyInto(out *CappList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Capp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappList.
func (in *CappList) DeepCopy() *CappList {
	if in == nil {
		return nil
	}
	out := new(CappList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CappList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappRevision) DeepCopyInto(out *CappRevision) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappRevision.
func (in *CappRevision) DeepCopy() *CappRevision {
	if in == nil {
		return nil
	}
	out := new(CappRevision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CappRevision) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappRevisionList) DeepCopyInto(out *CappRevisionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CappRevision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappRevisionList.
func (in *CappRevisionList) DeepCopy() *CappRevisionList {
	if in == nil {
		return nil
	}
	out := new(CappRevisionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CappRevisionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappRevisionSpec) DeepCopyInto(out *CappRevisionSpec) {
	*out = *in
	in.CappTemplate.DeepCopyInto(&out.CappTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappRevisionSpec.
func (in *CappRevisionSpec) DeepCopy() *CappRevisionSpec {
	if in == nil {
		return nil
	}
	out := new(CappRevisionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappRevisionStatus) DeepCopyInto(out *CappRevisionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappRevisionStatus.
func (in *CappRevisionStatus) DeepCopy() *CappRevisionStatus {
	if in == nil {
		return nil
	}
	out := new(CappRevisionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappSpec) DeepCopyInto(out *CappSpec) {
	*out = *in
	in.ConfigurationSpec.DeepCopyInto(&out.ConfigurationSpec)
	in.RouteSpec.DeepCopyInto(&out.RouteSpec)
	out.LogSpec = in.LogSpec
	in.VolumesSpec.DeepCopyInto(&out.VolumesSpec)
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]KedaSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappSpec.
func (in *CappSpec) DeepCopy() *CappSpec {
	if in == nil {
		return nil
	}
	out := new(CappSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappStatus) DeepCopyInto(out *CappStatus) {
	*out = *in
	out.ApplicationLinks = in.ApplicationLinks
	in.KnativeObjectStatus.DeepCopyInto(&out.KnativeObjectStatus)
	if in.RevisionInfo != nil {
		in, out := &in.RevisionInfo, &out.RevisionInfo
		*out = make([]RevisionInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.StateStatus.DeepCopyInto(&out.StateStatus)
	in.LoggingStatus.DeepCopyInto(&out.LoggingStatus)
	in.RouteStatus.DeepCopyInto(&out.RouteStatus)
	in.VolumesStatus.DeepCopyInto(&out.VolumesStatus)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SourceStatus != nil {
		in, out := &in.SourceStatus, &out.SourceStatus
		*out = make([]KedaStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappStatus.
func (in *CappStatus) DeepCopy() *CappStatus {
	if in == nil {
		return nil
	}
	out := new(CappStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CappTemplate) DeepCopyInto(out *CappTemplate) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CappTemplate.
func (in *CappTemplate) DeepCopy() *CappTemplate {
	if in == nil {
		return nil
	}
	out := new(CappTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSConfig) DeepCopyInto(out *DNSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSConfig.
func (in *DNSConfig) DeepCopy() *DNSConfig {
	if in == nil {
		return nil
	}
	out := new(DNSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRecordObjectStatus) DeepCopyInto(out *DNSRecordObjectStatus) {
	*out = *in
	in.CNAMERecordObjectStatus.DeepCopyInto(&out.CNAMERecordObjectStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRecordObjectStatus.
func (in *DNSRecordObjectStatus) DeepCopy() *DNSRecordObjectStatus {
	if in == nil {
		return nil
	}
	out := new(DNSRecordObjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KedaSource) DeepCopyInto(out *KedaSource) {
	*out = *in
	if in.ScalarMetadata != nil {
		in, out := &in.ScalarMetadata, &out.ScalarMetadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TriggerAuth != nil {
		in, out := &in.TriggerAuth, &out.TriggerAuth
		*out = new(TriggerAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KedaSource.
func (in *KedaSource) DeepCopy() *KedaSource {
	if in == nil {
		return nil
	}
	out := new(KedaSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KedaStatus) DeepCopyInto(out *KedaStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KedaStatus.
func (in *KedaStatus) DeepCopy() *KedaStatus {
	if in == nil {
		return nil
	}
	out := new(KedaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogSpec) DeepCopyInto(out *LogSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogSpec.
func (in *LogSpec) DeepCopy() *LogSpec {
	if in == nil {
		return nil
	}
	out := new(LogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingStatus) DeepCopyInto(out *LoggingStatus) {
	*out = *in
	in.SyslogNGFlow.DeepCopyInto(&out.SyslogNGFlow)
	in.SyslogNGOutput.DeepCopyInto(&out.SyslogNGOutput)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingStatus.
func (in *LoggingStatus) DeepCopy() *LoggingStatus {
	if in == nil {
		return nil
	}
	out := new(LoggingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NFSVolume) DeepCopyInto(out *NFSVolume) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NFSVolume.
func (in *NFSVolume) DeepCopy() *NFSVolume {
	if in == nil {
		return nil
	}
	out := new(NFSVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NFSVolumeStatus) DeepCopyInto(out *NFSVolumeStatus) {
	*out = *in
	out.NFSPVCStatus = in.NFSPVCStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NFSVolumeStatus.
func (in *NFSVolumeStatus) DeepCopy() *NFSVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(NFSVolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodIdentity) DeepCopyInto(out *PodIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodIdentity.
func (in *PodIdentity) DeepCopy() *PodIdentity {
	if in == nil {
		return nil
	}
	out := new(PodIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RevisionInfo) DeepCopyInto(out *RevisionInfo) {
	*out = *in
	in.RevisionStatus.DeepCopyInto(&out.RevisionStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RevisionInfo.
func (in *RevisionInfo) DeepCopy() *RevisionInfo {
	if in == nil {
		return nil
	}
	out := new(RevisionInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteSpec) DeepCopyInto(out *RouteSpec) {
	*out = *in
	in.TrafficTarget.DeepCopyInto(&out.TrafficTarget)
	if in.RouteTimeoutSeconds != nil {
		in, out := &in.RouteTimeoutSeconds, &out.RouteTimeoutSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteSpec.
func (in *RouteSpec) DeepCopy() *RouteSpec {
	if in == nil {
		return nil
	}
	out := new(RouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteStatus) DeepCopyInto(out *RouteStatus) {
	*out = *in
	in.DomainMappingObjectStatus.DeepCopyInto(&out.DomainMappingObjectStatus)
	in.DNSRecordObjectStatus.DeepCopyInto(&out.DNSRecordObjectStatus)
	in.CertificateObjectStatus.DeepCopyInto(&out.CertificateObjectStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteStatus.
func (in *RouteStatus) DeepCopy() *RouteStatus {
	if in == nil {
		return nil
	}
	out := new(RouteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StateStatus) DeepCopyInto(out *StateStatus) {
	*out = *in
	in.LastChange.DeepCopyInto(&out.LastChange)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StateStatus.
func (in *StateStatus) DeepCopy() *StateStatus {
	if in == nil {
		return nil
	}
	out := new(StateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerAuth) DeepCopyInto(out *TriggerAuth) {
	*out = *in
	if in.SecretTargets != nil {
		in, out := &in.SecretTargets, &out.SecretTargets
		*out = make([]AuthSecretTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvTargets != nil {
		in, out := &in.EnvTargets, &out.EnvTargets
		*out = make([]AuthEnvTarget, len(*in))
		copy(*out, *in)
	}
	if in.PodIdentity != nil {
		in, out := &in.PodIdentity, &out.PodIdentity
		*out = new(PodIdentity)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerAuth.
func (in *TriggerAuth) DeepCopy() *TriggerAuth {
	if in == nil {
		return nil
	}
	out := new(TriggerAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumesSpec) DeepCopyInto(out *VolumesSpec) {
	*out = *in
	if in.NFSVolumes != nil {
		in, out := &in.NFSVolumes, &out.NFSVolumes
		*out = make([]NFSVolume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumesSpec.
func (in *VolumesSpec) DeepCopy() *VolumesSpec {
	if in == nil {
		return nil
	}
	out := new(VolumesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumesStatus) DeepCopyInto(out *VolumesStatus) {
	*out = *in
	if in.NFSVolumesStatus != nil {
		in, out := &in.NFSVolumesStatus, &out.NFSVolumesStatus
		*out = make([]NFSVolumeStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumesStatus.
func (in *VolumesStatus) DeepCopy() *VolumesStatus {
	if in == nil {
		return nil
	}
	out := new(VolumesStatus)
	in.DeepCopyInto(out)
	return out
}
