apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "container-app-operator.fullname" . }}-rcs-cappconfig-editor-role
  labels:
  {{- include "container-app-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - rcs.dana.io
  resources:
  - cappconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rcs.dana.io
  resources:
  - cappconfigs/status
  verbs:
  - get